config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo/로 시작되는 페이지 요청은 모두 pybo/urls.py에 있는 URL 매핑을 참고하여 처리하라는 의미
]

pybo/urls.py
from django.urls import path
from . import views

# urls.py는 페이지 요청 시 가장 먼저 호출되며 요청 url과 뷰 함수를 1:1로 연결해준다

app_name = 'pybo' # namespace 사용함

urlpatterns =[
    path('', views.index, name='index'), # views.index: views.py파일의 index함수를 의미한다
    # config/urls.py에서 pybo/에 대한 처리를 했으므로 ''를 넘겨주어야 한다
    # 맨 뒤에 항상 쉼표를 달자
    path('<int:question_id>/', views.detail, name='detail'), # URL매핑에 name 속성을 부여한다
    path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'), # url 마지막에는 / 붙이는걸 습관화 하자
]

pybo/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
"""
질문모델: subject, content, create_date
답변모델: question, content, create_date
"""

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self): # Object 1 이렇게 반환되는게 아니라 subject가 바로 나오도록 magic method 구현
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/forms.py
from socket import fromshare
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    """
    장고 폼 (모델 폼)
    """
    class Meta:
        model = Question
        fields = ['subject', 'content']
        """
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control', 'rows': 10}),
        }
        수작업으로 HTML을 만들어서 디자인적인것을 넣기 위해선 이렇게 하면 안된다
        """
        labels = {
            'subject': 'Input subject!', # 여기서 label을 입력한거랑 html에서 입력한거랑 적용되는데가 다른가?
            'content': 'Input content!',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'answer'
        }

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.

from django.http import HttpResponse
from .models import Answer, Question
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator # 페이징 기능 추가 위한 모듈

def index(request): # request: django에 의해 자동으로 전달되는 HTTP 요청 객체
    """
    목록 출력
    """
    # 입력
    page = request.GET.get('page', '1')
    
    #조회
    question_list = Question.objects.order_by('-create_date')
    
    # 페이징 처리
    paginator = Paginator(question_list, 10) # 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context) # 페이지 요청에 대한 응답
    # render 함수는 context에 있는 Question 모델 데이터 question_list를 HTML에 적용

def detail(request, question_id):
    """
    내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    """
    답변 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    # answer model을 사용해서 데이터를 저장할 수도 있다

    return 

def question_create(request):
    """
    질문 등록
    """
    if request.method == "POST": # POST라면 화면에서 전달받은 데이터로 폼의 값이 채워지도록 객체를 생성
        form = QuestionForm(request.POST)
        if form.is_valid(): # 요청받은 form이 유효한지 검사
            question = form.save(commit=False) # form으로 Question 모델 데이터를 저장하기 위한 코드, commit=False는 임시저장을 의미, 아래에서 date를 받고난 뒤에 저장하도록 하기 위해?
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else: # GET 방식이라면 입력값 없이 객체를 생성
        form = QuestionForm()
    context = {'form': form} # {'form': form}은 폼엘리먼트를 생성할 때 사용
    return render(request, 'pybo/question_form.html', context) 

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=divice-width, initial-scale=1, shrink-to-fit=no">
        <!-- 부트스트랩 적용, 여기선 4.6.2버전, 최신버전이 아님, 책에서 이렇게 해서 그냥 일단 적용해봄 -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <!-- 제작한 css 파일 적용 -->
        <link rel="stylesheet" href="text/css" href="{% static 'style.css' %}">
        <!-- JQuery and popper bundle -> 네비개이션 햄버거버튼 작동에 필요함 -->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
        <Title>Hello world!</Title>
    </head>
    <body>
        <!-- Navigation bar -->
        {% include "navbar.html" %}

        <!-- base template start-->
        {% block content %}
        <!-- 이 파일을 상속받은 html 파일에서 작성하는 영역-->
        {% endblock %}
        <!-- base template end-->
    </body>
</html>

templates/navbar.html
<!-- NAVIGATION BAR -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">PYBO</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <a class="nav-link" href="#">Login</a>
        </ul>
    </div>
</nav>

templates/pybo/question_detail.html
<!-- 기본 base.html을 상속받아옴 -->
{% extends 'base.html' %} 

<!-- 그 안에 구현하는 부분 작성 -->
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
        <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2">{{ question.create_date }}</div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }} answers are exist
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space:pre-line;">{{ answer.content}}</div>
        </div>
        <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2">{{ answer.create_date }}</div>
        </div>
    </div> 
    {% endfor %}

    <!-- 답변 등록 버튼 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %} <!-- 보안관련, form으로 전송된 데이터가 실제 웹 브라우저에서 작성된것인지 검사하는 역할, form 바로 아래에 항상 입력해야 한다-->
        <!-- 오류표시 -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="context" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="Answer" class="btn btn-primary">
    </form>
</div>

{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Add question</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- {{ form.as_p }}를 사용하면 간단하게 만들수 있지만, 디자인 측면에서 제한이 생기게 된다 -->
        <!-- 오류표시 -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <label for="subject">Input subject</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="content">Input content</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

{% endblock %}

templates/pybo/question_list.html
<!-- 기본 base.html을 상속받아옴 -->
{% extends 'base.html' %} 

<!-- 그 안에 구현하는 부분 작성 -->
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>Number</th>
                <th>Subject</th>
                <th>Date</th>
            </tr>
        </thead>
        <body>
            {% if question_list %}
            {% for question in question_list %} 
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                </td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
            
            {% else %}
                <tr>
                    <td colspan="3">No question</td>
                </tr>
            {% endif %}            
        </body>
    </table>
    <!-- paging -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">Prev</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-diabled="true" href="#">Prev</a>
        </li>
        {% endif %}
        <!-- Page list -->
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page= {{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-diabled="true" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
    <!-- add question -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">Add question</a>
</div>

{% endblock %}



<!-- 부트스트랩 적용 전 
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li> namespace와 별칭을 사용
            <li><a href="/pybo/{{ question.id }}/">{{ question.subject }}</a></li>  URL 하드코딩스타일
        {% endfor %}
    </ul>
{% else %}
    <p>No question</p>

{% endif %}
-->